Doxygen Fortran Example: hhg.f90 File Reference
hhg.f90 File Reference
Functions/Subroutines
program calculation_hhg
Function/Subroutine Documentation
program calculation_hhg ()
Definition at line 3 of file hhg.f90.
References vars::acc_dip, vars::alloc_arr_xy(), vars::clr_vars(), vars::cre_vars(), vars::d2z, vars::dealloc_arr_xy(), deriv_dip::deriv(), vars::dip, vars::dz, vars::hhg, vars::hhgodd, vars::hhgs, vars::ntmax, vars::order, vars::out_acc, vars::out_dip, vars::out_grd, vars::out_vec, vars::phase, pars::pi, read_inputs::read_pars(), deriv_dip::second_deriv(), vars::sigma, vars::theta, vars::theta_max, vars::theta_min, vars::theta_step, vars::timestep, hhg_mod::wrt_hhg(), and hhg_mod::wrt_pha().