Doxygen Fortran Example: pars Module Reference
pars Module Reference
Variables
integer, parameter dp = 8
real(dp), parameter pi = acos(-1.0_dp)
real(dp), parameter aui = 351.3393_dp
real(dp), parameter aue = 27.21138457_dp
Variable Documentation
real(dp), parameter pars::aue = 27.21138457_dp
Definition at line 7 of file pars.f90.
Referenced by read_inputs::read_pars().
         real(dp), parameter :: aue =  27.21138457_dp     ! Energy in eV (1 a.u. = 27.2113 eV)
real(dp), parameter pars::aui = 351.3393_dp
Definition at line 6 of file pars.f90.
Referenced by read_inputs::read_pars().
         real(dp), parameter :: aui = 351.3393_dp                 ! Intensity in 10^14 W/cm^2
integer, parameter pars::dp = 8
Definition at line 4 of file pars.f90.
         integer,  parameter :: dp = 8
real(dp), parameter pars::pi = acos(-1.0_dp)
Definition at line 5 of file pars.f90.
Referenced by hhg_mod::calc_hhg(), calculation_hhg(), and read_inputs::read_pars().
         real(dp), parameter :: pi = acos(-1.0_dp)