Doxygen Fortran Example: hhg_mod Module Reference
hhg_mod Module Reference
Data Types
interface calc_hhg
Functions/Subroutines
subroutine calc_hhg_arr_xy (ho, dip, hhg, hhgodd, hhgs, phase)
subroutine calc_hhg (ho, dip, hhg, hhgodd, hhgs, phase)
subroutine calc_hhg_smooth (hhg, hhg_smooth)
subroutine calc_odd_hhg (ho, hhg, hhgo)
subroutine wrt_hhg (fln1, fln2, ho, hhg, hhgo, hhgs, iangle)
subroutine wrt_pha (fln, ho, phase, iangle)
Function/Subroutine Documentation
subroutine hhg_mod::calc_hhg (real(dp), dimension(:), intent(in) ho, real(dp), dimension(:), intent(in) dip, real(dp), dimension(size(ho)), intent(out) hhg, real(dp), dimension(:), intent(out) hhgodd, real(dp), dimension(size(hhg)), intent(out) hhgs, real(dp), dimension(size(hhg)), intent(out) phase)
Definition at line 26 of file hhg_mod.f90.
References calc_hhg_smooth(), calc_odd_hhg(), vars::hhg, vars::hhgodd, vars::hhgs, vars::nhhgmax, vars::omega0, pars::pi, and vars::timestep.
         real(dp), intent(in)  :: ho(:), dip(:)
         real(dp), intent(out) :: hhgodd(:)
         real(dp), intent(out) :: hhg(size(ho)), hhgs(size(hhg)), phase(size(hhg))
         real(dp) :: omegamax, omega, omega_t
         real(dp) :: signal_real, signal_imag
         integer :: i, j
         omegamax = pi/timestep
         if ( nhhgmax*omega0 >= omegamax ) then
        write(*,*) 'Please increase the value of Nt!'
        stop
     endif
 block
     integer :: ndip
     real(8) :: time(0:size(dip))
     ndip = size(dip)
     time = [0:ndip]*timestep
     do i = 1, size(hhg)
                 omega = ho(i) * omega0
 !               signal_real = 0.0_dp
 !               signal_imag = 0.0_dp
 !               do j = 0, size(dip)
 !--                     omega_t = order(i)*omega0 * dble(j)*TimeStep
 !                       omega_t = omega * dble(j)*TimeStep
 !                       signal_real = signal_real + dip(j) * cos(omega_t)
 !                       signal_imag = signal_imag + dip(j) * sin(omega_t)
 !               enddo
                 signal_real = sum( dip(0:ndip) * cos( time * omega ) )
                 signal_imag = sum( dip(0:ndip) * sin( time * omega ) )
 !               hhg(i) = TimeStep*TimeStep * abs(sum( dip(0:ndip) * exp( time * omega ) ) )
 !               hhg(i) = TimeStep**2 * abs(signal)
                 hhg(i) = timestep**2 * (signal_real**2 + signal_imag**2)
                 if (hhg(i) == 0.0_dp) hhg(i) = 1.0d-6
                 phase(i) = atan2(signal_imag, signal_real) * 180.0_dp/pi
     enddo
 end block
     call calc_odd_hhg(ho, hhg, hhgodd)
     call calc_hhg_smooth(hhg, hhgs)
subroutine hhg_mod::calc_hhg_arr_xy (real(dp), dimension(:), intent(in) ho, type(arr_xy), intent(in) dip, type(arr_xy), intent(inout) hhg, type(arr_xy), intent(inout) hhgodd, type(arr_xy), intent(inout) hhgs, type(arr_xy), intent(inout) phase)
Definition at line 15 of file hhg_mod.f90.
     real(dp),     intent(in)    :: ho(:)
     type(arr_xy), intent(in)    :: dip
     type(arr_xy), intent(inout) :: hhg, hhgodd, hhgs, phase
     call calc_hhg(ho, dip%x, hhg%x, hhgodd%x, hhgs%x, phase%x)
     call calc_hhg(ho, dip%y, hhg%y, hhgodd%y, hhgs%y, phase%y)
subroutine hhg_mod::calc_hhg_smooth (real(dp), dimension(:), intent(in) hhg, real(dp), dimension(size(hhg)), intent(out) hhg_smooth)
Definition at line 88 of file hhg_mod.f90.
Referenced by calc_hhg().
         real(dp), intent(in)  :: hhg(:)
         real(dp), intent(out) :: hhg_smooth(size(hhg))
         real(dp)  :: omega, omega_p, alpha, omega_step, phase_temp
         integer :: i, j
     alpha = sigma * omega0
         omega_step = dble(nhhgmax) / npts_hhg
         do i = 1, size(hhg)
                 hhg_smooth(i) = 0.0_dp
                 omega = dble(i) * omega_step * omega0
                 do j = 1, size(hhg)
                         omega_p = dble(j) * omega_step * omega0
                         phase_temp = - 1.0_dp * (omega_p - omega)**2 / alpha**2
                         hhg_smooth(i) = hhg_smooth(i) + hhg(j) * exp(phase_temp)
                 enddo
                 hhg_smooth(i) = hhg_smooth(i) * omega_step * omega0
                 if (hhg_smooth(i) == 0.0_dp) hhg_smooth(i) = 1.0d-6
         enddo
subroutine hhg_mod::calc_odd_hhg (real(8), dimension(:), intent(in) ho, real(8), dimension(:), intent(in) hhg, real(8), dimension(:), intent(out) hhgo)
Definition at line 114 of file hhg_mod.f90.
Referenced by calc_hhg().
     real(8), intent(in)  :: ho(:), hhg(:)
     real(8), intent(out) :: hhgo(:)
     real(8) :: delta
     integer :: nhhg
     integer :: n, io
     nhhg = nint( ho(size(ho)) )
 !    write(*,*) NhhgMax
     delta = ho(2) - ho(1)
 block
     logical :: mask(1:size(ho))
     do n = 1, nhhg, 2
         mask = ho >= dble(n-1) .and. ho < dble(n+1)
         hhgo(n) = sum( hhg, mask = mask )
     enddo
     hhgo = hhgo * delta
 end block
subroutine hhg_mod::wrt_hhg (character, dimension(*), intent(in) fln1, character, dimension(*), intent(in) fln2, real(dp), dimension(:), intent(in) ho, type(arr_xy), intent(in) hhg, type(arr_xy), intent(in) hhgo, type(arr_xy), intent(in) hhgs, integer, intent(in) iangle)
Definition at line 143 of file hhg_mod.f90.
Referenced by calculation_hhg().
     character, intent(in) :: fln1*(*), fln2*(*)
     integer,   intent(in) :: iangle
     real(dp),  intent(in) :: ho(:)
     type(arr_xy), intent(in) :: hhg, hhgo, hhgs
     character :: nameout*100
     integer   :: idfln
     integer   :: k
     write(nameout, '(a,i0,a)') trim(fln1)// '-', iangle, '.dat'
 !    print*, nameout, size(ho), size(hhg%x), size(hhg%y), size(hhgs%x), size(hhgs%y)
     open(newunit = idfln, file = nameout)
         write(idfln, '(5(E16.8,X))') ( ho(k), hhg%x(k), hhgs%x(k), &
                                                                                   hhg%y(k), hhgs%y(k), k = 1, size(ho) )
     close(unit = idfln)
 !--
     write(nameout, '(a,i0,a)') trim(fln2)// '-', iangle, '.dat'
     open(newunit = idfln, file = nameout)
         write(idfln, '(I, 4E16.8)') ( k, hhgo%x(k), log(hhgo%x(k)), &
                                                                              hhgo%y(k), log(hhgo%y(k)), k = 1, size(hhgo%x), 2 )
     close(unit = idfln)
subroutine hhg_mod::wrt_pha (character, dimension(*), intent(in) fln, real(dp), dimension(:), intent(in) ho, type(arr_xy), intent(in) phase, integer, intent(in) iangle)
Definition at line 175 of file hhg_mod.f90.
Referenced by calculation_hhg().
     character, intent(in) :: fln*(*)
     integer,   intent(in) :: iangle
     real(dp),  intent(in) :: ho(:)
     type(arr_xy), intent(in) :: phase
     character :: nameout*100
     integer   :: idfln
     integer   :: k
     write(nameout, '(a,i0,a)') trim(fln)// '-', iangle, '.dat'
     open(newunit = idfln, file = nameout)
         write(idfln, '(3(E16.8,X))') ( ho(k), phase%x(k), phase%y(k), k = 1, size(ho) )
     close(unit = idfln)