Doxygen Fortran Example: vars Module Reference
vars Module Reference
Data Types
type arr_xy
Functions/Subroutines
subroutine alloc_arr_xy (arr, b1, b2)
subroutine dealloc_arr_xy (arr)
subroutine cre_vars ()
subroutine clr_vars ()
Variables
integer ncycle
integer nt
integer ntmax
integer nhhgmax
integer npts_hhg
integer theta_min
integer theta_max
integer theta_step
real(dp) timefwhm
real(dp) timestep
real(dp) i0
real(dp) evec0
real(dp) omega0
real(dp) phacep
real(dp) up
real(dp) ip
real(dp) theta
logical out_dip
logical out_vec
logical out_acc
logical out_grd
real(dp), dimension(:), allocatable order
real(dp) sigma
real(dp) domega
type(arr_xy) acc_dip
type(arr_xy) dip
type(arr_xy) dz
type(arr_xy) d2z
type(arr_xy) hhg
type(arr_xy) hhgs
type(arr_xy) hhgodd
type(arr_xy) phase
Function/Subroutine Documentation
subroutine vars::alloc_arr_xy (type(arr_xy), intent(inout) arr, integer, intent(in) b1, integer, intent(in), optional b2)
Definition at line 31 of file vars.f90.
Referenced by calculation_hhg(), and cre_vars().
   type(arr_xy), intent(inout) :: arr
   integer,   intent(in)  :: b1, b2
   optional :: b2
   integer  :: lb, ub
   if ( present(b2) ) then
     lb = b1
     ub = b2
   else
     lb = 1
     ub = b1
   endif
   if( allocated(arr%x) ) deallocate( arr%x )
   allocate( arr%x(lb:ub) )
   if( allocated(arr%y) ) deallocate( arr%y )
   allocate( arr%y(lb:ub) )
subroutine vars::clr_vars ()
Definition at line 76 of file vars.f90.
References acc_dip, dealloc_arr_xy(), dip, hhg, hhgodd, hhgs, order, and phase.
Referenced by calculation_hhg().
         if(allocated(order)) deallocate( order )
         call dealloc_arr_xy( acc_dip )
         call dealloc_arr_xy( dip )
         call dealloc_arr_xy( hhg )
         call dealloc_arr_xy( hhgs )
         call dealloc_arr_xy( phase )
     call dealloc_arr_xy( hhgodd )
subroutine vars::cre_vars ()
Definition at line 63 of file vars.f90.
References alloc_arr_xy(), hhg, hhgodd, hhgs, nhhgmax, npts_hhg, order, and phase.
Referenced by calculation_hhg().
     allocate( order(npts_hhg) )
         order(:) = dble((/1:npts_hhg/)) * nhhgmax/npts_hhg !!!
     call alloc_arr_xy( hhg,    npts_hhg )
     call alloc_arr_xy( hhgs,   npts_hhg )
     call alloc_arr_xy( phase,  npts_hhg )
     call alloc_arr_xy( hhgodd, nhhgmax )
subroutine vars::dealloc_arr_xy (type(arr_xy), intent(inout) arr)
Definition at line 54 of file vars.f90.
Referenced by calculation_hhg(), and clr_vars().
     type(arr_xy), intent(inout) :: arr
     if ( allocated(arr%x) ) deallocate( arr%x )
     if ( allocated(arr%y) ) deallocate( arr%y )
Variable Documentation
type(arr_xy) vars::acc_dip
Definition at line 20 of file vars.f90.
Referenced by calculation_hhg(), and clr_vars().
         type(arr_xy) :: acc_dip, dip
type(arr_xy) vars::d2z
Definition at line 21 of file vars.f90.
Referenced by calculation_hhg().
type(arr_xy) vars::dip
Definition at line 20 of file vars.f90.
Referenced by calculation_hhg(), and clr_vars().
real(dp) vars::domega
Definition at line 14 of file vars.f90.
Referenced by read_inputs::read_pars().
type(arr_xy) vars::dz
Definition at line 21 of file vars.f90.
Referenced by calculation_hhg().
         type(arr_xy) :: dz, d2z
real(dp) vars::evec0
Definition at line 8 of file vars.f90.
Referenced by read_inputs::read_pars().
type(arr_xy) vars::hhg
Definition at line 22 of file vars.f90.
Referenced by hhg_mod::calc_hhg(), calculation_hhg(), clr_vars(), and cre_vars().
         type(arr_xy) :: hhg, hhgs, hhgodd !!!!! 11Apr
type(arr_xy) vars::hhgodd
Definition at line 22 of file vars.f90.
Referenced by hhg_mod::calc_hhg(), calculation_hhg(), clr_vars(), and cre_vars().
type(arr_xy) vars::hhgs
Definition at line 22 of file vars.f90.
Referenced by hhg_mod::calc_hhg(), calculation_hhg(), clr_vars(), and cre_vars().
real(dp) vars::i0
Definition at line 8 of file vars.f90.
Referenced by read_inputs::read_pars().
real(dp) vars::ip
Definition at line 9 of file vars.f90.
Referenced by read_inputs::read_pars().
integer vars::ncycle
Definition at line 5 of file vars.f90.
Referenced by read_inputs::read_pars().
         integer :: ncycle, nt, ntmax
integer vars::nhhgmax
Definition at line 6 of file vars.f90.
Referenced by hhg_mod::calc_hhg(), cre_vars(), and read_inputs::read_pars().
         integer :: nhhgmax, npts_hhg
integer vars::npts_hhg
Definition at line 6 of file vars.f90.
Referenced by cre_vars(), and read_inputs::read_pars().
integer vars::nt
Definition at line 5 of file vars.f90.
Referenced by read_inputs::read_pars().
integer vars::ntmax
Definition at line 5 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
real(dp) vars::omega0
Definition at line 8 of file vars.f90.
Referenced by hhg_mod::calc_hhg(), and read_inputs::read_pars().
real(dp), dimension(:), allocatable vars::order
Definition at line 13 of file vars.f90.
Referenced by calculation_hhg(), clr_vars(), and cre_vars().
         real(dp), allocatable :: order(:)
logical vars::out_acc
Definition at line 11 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
logical vars::out_dip
Definition at line 11 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
         logical :: out_dip, out_vec, out_acc, out_grd
logical vars::out_grd
Definition at line 11 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
logical vars::out_vec
Definition at line 11 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
real(dp) vars::phacep
Definition at line 8 of file vars.f90.
Referenced by read_inputs::read_pars().
type(arr_xy) vars::phase
Definition at line 23 of file vars.f90.
Referenced by calculation_hhg(), clr_vars(), and cre_vars().
         type(arr_xy) :: phase
real(dp) vars::sigma
Definition at line 14 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
         real(dp)  :: sigma, domega
real(dp) vars::theta
Definition at line 9 of file vars.f90.
Referenced by calculation_hhg().
integer vars::theta_max
Definition at line 7 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
integer vars::theta_min
Definition at line 7 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
         integer :: theta_min, theta_max, theta_step
integer vars::theta_step
Definition at line 7 of file vars.f90.
Referenced by calculation_hhg(), and read_inputs::read_pars().
real(dp) vars::timefwhm
Definition at line 8 of file vars.f90.
Referenced by read_inputs::read_pars().
         real(dp) :: timefwhm, timestep, i0, evec0, omega0, phacep
real(dp) vars::timestep
Definition at line 8 of file vars.f90.
Referenced by hhg_mod::calc_hhg(), calculation_hhg(), and read_inputs::read_pars().
real(dp) vars::up
Definition at line 9 of file vars.f90.
Referenced by read_inputs::read_pars().
         real(dp) :: up, ip, theta